export function createMapCatalog() {
  const MAPS = [
                {name:"NEON DISTRICT", subtitle:"Mid-rise blocks and crossfire lanes", spawn:[0,1.7,58]},
                {name:"DOCKSIDE", subtitle:"Warehouse roofs, cranes, and cargo gaps", spawn:[-48,1.7,48]},
                {name:"BLACKSITE", subtitle:"Fortified courtyards and breach routes", spawn:[48,1.7,48]},
                {name:"QUARRY TOWN", subtitle:"Broken elevation, ramps, and quarry cuts", spawn:[0,1.7,58]},
                {name:"RAIL YARD", subtitle:"Rail warehouses and crossing platforms", spawn:[-48,1.7,-48]},
                {name:"REACTOR CITY", subtitle:"Cooling blocks and vertical corridors", spawn:[48,1.7,-48]},
                {name:"MARKET RUINS", subtitle:"Tight alleys, awnings, and plazas", spawn:[-4,1.7,58]},
                {name:"AIRBASE", subtitle:"Hangars, runway jumps, and tower routes", spawn:[-58,1.7,0]},
                {name:"FLOODZONE", subtitle:"Raised blocks and flooded gaps", spawn:[54,1.7,4]},
                {name:"SKYBRIDGE", subtitle:"Suspended crossings between tower blocks", spawn:[0,1.7,58]},
                {name:"CARGO GRID", subtitle:"Container streets and stacked routes", spawn:[-58,1.7,4]},
                {name:"OLD TOWN", subtitle:"Low roofs, courtyards, and wall runs", spawn:[58,1.7,-4]},
                {name:"NIGHT MARKET", subtitle:"Narrow stalls and neon rooftop lanes", spawn:[-50,1.7,46]},
                {name:"CONCRETE MAZE", subtitle:"Chunky blocks with vault corridors", spawn:[46,1.7,46]},
                {name:"FORTRESS", subtitle:"Layered walls and elevated strongpoints", spawn:[-46,1.7,-46]},
                {name:"SUBSTATION", subtitle:"Utility towers, catwalks, and cable routes", spawn:[46,1.7,-46]},
                {name:"MILL DISTRICT", subtitle:"Factory blocks and overhead conveyors", spawn:[0,1.7,-58]},
                {name:"TERMINAL", subtitle:"Travel halls and terminal jump lines", spawn:[-58,1.7,-4]},
                {name:"VERTIGO", subtitle:"Tall rooftops linked by precision jumps", spawn:[0,1.7,56]},
                {name:"SUNKEN PLAZA", subtitle:"Lower streets with rooftop escape routes", spawn:[-52,1.7,0]},
                {name:"ROOFTOP PARK", subtitle:"Open roofs, launch pads, and long gaps", spawn:[52,1.7,0]},
                {name:"CANAL RUN", subtitle:"Canals, wall hops, and narrow bridges", spawn:[0,1.7,-56]},
                {name:"SKYHOOK", subtitle:"Grapple-friendly towers and swing lanes", spawn:[-50,1.7,-46]},
                {name:"FREIGHT HILLS", subtitle:"Layered freight stacks and moving floors", spawn:[50,1.7,46]},
                {name:"GLASSWORKS", subtitle:"Bright slabs, transparent-looking lanes, and leaps", spawn:[-46,1.7,50]},
                {name:"UNDERPASS", subtitle:"Low tunnels opening into tall parkour towers", spawn:[46,1.7,50]},
                {name:"EDGE CITY", subtitle:"Perimeter roofs with dangerous shortcut routes", spawn:[0,1.7,58]},
                {name:"CRANE ROW", subtitle:"Cranes, suspended decks, and vertical climbs", spawn:[-58,1.7,-2]},
                {name:"TILT YARD", subtitle:"Sloped routes and staggered rooftop heights", spawn:[58,1.7,2]},
                {name:"PULSE SECTOR", subtitle:"Energy platforms and timed crossings", spawn:[-4,1.7,-58]},
                {name:"BREACH BLOCK", subtitle:"Breachable-looking courtyards and speed lanes", spawn:[4,1.7,58]},
                {name:"OVERPASS", subtitle:"Layered roads with rooftop shortcuts", spawn:[-58,1.7,52]},
                {name:"SKYLINE 99", subtitle:"Extreme vertical routes above the skyline", spawn:[58,1.7,-52]},
                {name:"DEADLINE", subtitle:"Long sightlines split by rapid vault chains", spawn:[-52,1.7,58]},
                {name:"ARC YARD", subtitle:"Curved-feeling lanes built from staggered decks", spawn:[52,1.7,58]},
                {name:"UPLINK", subtitle:"Antennas, towers, and launch-pad routes", spawn:[0,1.7,-58]}
              ];
  const MAP_LAYOUT_TYPES = [
                "grid","offset","courtyard","cross","warehouse","diagonal","rings","hangar",
                "stagger","bridge","cargo","oldtown","alley","concrete","fortress","utility",
                "factory","terminal","spiral","checker","canyon","plaza","towers","switchback",
                "zigzag","islands","central","perimeter","rooftop","split","trident","labyrinth",
                "corridor","terraces","funnel","arena"
              ];
  const MAP_IDENTITY_10 = Object.freeze([
                { key:'neon',      name:'Crossfire Grid',    features:['crossfire lanes','mid-height flank cover'], profile:'sightline' },
                { key:'dockside',  name:'Cargo Swing',       features:['container jumps','moving cargo lane'], profile:'moving' },
                { key:'blacksite', name:'Breach Routes',     features:['interior breach lane','high ground'], profile:'interior' },
                { key:'quarry',    name:'Broken Elevation',  features:['staggered heights','jump shortcuts'], profile:'precision' },
                { key:'railyard',  name:'Rail Crossing',     features:['crossing platforms','long sightline'], profile:'bridge' },
                { key:'reactor',   name:'Vertical Core',     features:['vertical ascent','elevator route'], profile:'vertical' },
                { key:'market',    name:'Alley Run',         features:['tight flanks','roof escape'], profile:'rooftop' },
                { key:'airbase',   name:'Runway Launch',     features:['launch pads','tower perch'], profile:'launch' },
                { key:'floodzone', name:'Raised Escape',     features:['raised route','low-ground danger'], profile:'vertical' },
                { key:'skybridge', name:'Sky Crossing',      features:['narrow bridges','grapple shortcut'], profile:'grapple' },
                { key:'cargo',     name:'Stacked Cargo',     features:['stacked cover','vault chain'], profile:'precision' },
                { key:'oldtown',   name:'Wall Run District', features:['long wall runs','roof hops'], profile:'wallrun' },
                { key:'night',     name:'Neon Roofline',     features:['roofline chain','grapple flank'], profile:'rooftop' },
                { key:'maze',      name:'Vault Maze',        features:['vault corridors','crossfire pockets'], profile:'interior' },
                { key:'fortress',  name:'Fortified Heights', features:['interior/exterior split','strongpoints'], profile:'fortress' },
                { key:'substation',name:'Cable Climb',      features:['vertical cable towers','moving catwalk'], profile:'vertical' },
                { key:'mill',      name:'Conveyor Run',      features:['moving floors','overhead route'], profile:'moving' },
                { key:'terminal',  name:'Terminal Lines',    features:['precision jump lines','open sightline'], profile:'precision' },
                { key:'vertigo',   name:'Vertigo',           features:['extreme verticality','launch ascent'], profile:'vertical' },
                { key:'sunken',    name:'Rooftop Escape',    features:['low street','fast roof route'], profile:'rooftop' },
                { key:'roofpark',  name:'Rooftop Park',      features:['chain movement','long gaps'], profile:'rooftop' },
                { key:'canal',     name:'Canal Run',         features:['extended wall runs','narrow bridges'], profile:'wallrun' },
                { key:'skyhook',   name:'Skyhook',           features:['grapple lanes','swing shortcuts'], profile:'grapple' },
                { key:'freight',   name:'Freight Movers',    features:['moving floors','layered stacks'], profile:'moving' },
                { key:'glass',     name:'Glass Leap',        features:['precision jumps','bright sightlines'], profile:'precision' },
                { key:'underpass', name:'Underpass Towers',  features:['interior/exterior transition','vertical exit'], profile:'interior' },
                { key:'edge',      name:'Edge Shortcuts',    features:['perimeter route','high-risk shortcut'], profile:'bridge' },
                { key:'crane',     name:'Crane Climb',       features:['vertical climbs','suspended deck'], profile:'vertical' },
                { key:'tilt',      name:'Tilt Route',        features:['sloped route','staggered heights'], profile:'precision' },
                { key:'pulse',     name:'Timed Crossings',   features:['timed platforms','launch route'], profile:'moving' },
                { key:'breach',    name:'Speed Breach',      features:['speed lane','breach courtyard'], profile:'launch' },
                { key:'overpass',  name:'Layered Roads',     features:['road layers','rooftop shortcut'], profile:'bridge' },
                { key:'skyline',   name:'Skyline 99',        features:['extreme verticality','high-ground combat'], profile:'vertical' },
                { key:'deadline',  name:'Vault Chain',       features:['rapid vault chain','precision sightline'], profile:'precision' },
                { key:'arc',       name:'Staggered Arc',     features:['staggered decks','flank loop'], profile:'precision' },
                { key:'uplink',    name:'Uplink',            features:['antenna ascent','launch-pad route'], profile:'launch' },
              ]);
  return { MAPS, MAP_LAYOUT_TYPES, MAP_IDENTITY_10 };
}
