import * as THREE from 'three';
import { MAX_STAMINA } from '../config/tuning.js';

export function createMovementState() {
  return {
    velocityY: 0,
    grounded: true,
    moveVelocityX: 0,
    moveVelocityZ: 0,
    mantling: false,
    mantleTimer: 0,
    mantleDuration: 0.28,
    mantleObstacle: null,
    mantleStartPosition: new THREE.Vector3(),
    mantleEndPosition: new THREE.Vector3(),
    mantleDirection: new THREE.Vector3(),
    stamina: MAX_STAMINA,
    staminaRegenDelay: 0,
    sprintExhausted: false,
    staminaWarningCooldown: 0,
    jumpCutGraceTimer: 0,
    wallRunning: false,
    wallRunTimer: 0,
    wallRunNormal: new THREE.Vector3(),
    jumpHeld: false,
    jumpCutApplied: false,
    airJumpAvailable: false,
    groundPoundActive: false,
    climbingWall: false,
    climbingObstacle: null,
    wallClimbGraceTimer: 0,
    sliding: false,
    slideTimer: 0,
    slideCooldown: 0,
    coyoteTimer: 0,
    jumpBufferTimer: 0,
    vaulting: false,
    vaultTimer: 0,
    vaultCooldown: 0,
    vaultObstacle: null,
    mantleCooldown: 0,
    wallJumpCooldown: 0,
    wasGrounded: true,
    slideDirection: new THREE.Vector3(),
    dashCooldown: 0,
    dashFlash: 0,
    dashActiveTime: 0,
    dashDirection: new THREE.Vector3(),
    dashSpeed: 0,
  };
}
